# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Test
run-name: "test run"

on:
  workflow_dispatch:

jobs:
  distribute:
    permissions:
      id-token: write
      contents: read
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/family=m8+c8/tag=infra
    steps:
      - name: Create a GitHub OIDC JWT
        id: create-github-jwt
        shell: bash
        run: |
          set -euo pipefail
          url="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://releases-stage.apache.org/"
          jwt="$(curl -sS --fail-with-body -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "$url" | jq -r .value)"
          echo "::add-mask::$jwt"
          echo "jwt=$jwt" >> "$GITHUB_OUTPUT"


      - name: Generate an ephemeral SSH key
        id: generate-ssh-key
        shell: bash
        run: |
          set -euxo pipefail
          ssh-keygen -t ed25519 -N "" -f "$RUNNER_TEMP/ssh_key"
          echo "ssh_private_key_path=$RUNNER_TEMP/ssh_key" >> "$GITHUB_OUTPUT"
          echo "ssh_public_key=$(cat "$RUNNER_TEMP/ssh_key.pub")" >> "$GITHUB_OUTPUT"

      - name: Register the ephemeral SSH key with ATR
        shell: bash
        run: |
          set -euxo pipefail
          jq -n --arg publisher github \
                --arg jwt "$JWT" \
                --arg key "$SSH_PUBLIC_KEY" \
                '{publisher:$publisher, jwt:$jwt, ssh_key:$key}' |
            curl -sS --fail-with-body -X POST -H 'Content-Type: application/json' -d @- \
              "https://releases-stage.apache.org/api/publisher/ssh/register"
        env:
          JWT: ${{ steps.create-github-jwt.outputs.jwt }}
          SSH_PUBLIC_KEY: ${{ steps.generate-ssh-key.outputs.ssh_public_key }}

      - name: Download from ATR using rsync
        shell: bash
        run: |
          command -v rsync > /dev/null || { sudo apt-get update -y && sudo apt-get install -y rsync; }
          rsync -av \
            -e "ssh -p 2222 -i $SSH_PRIVATE_KEY_PATH -o StrictHostKeyChecking=accept-new" \
            -- \
            "github@releases-stage.apache.org:/tooling-actions/0.1/" ./
        env:
          SSH_PRIVATE_KEY_PATH: ${{ steps.generate-ssh-key.outputs.ssh_private_key_path }}
